### ISSUE TITLE
Peer Review dg222cs

### ISSUE THREAD

**Issue by Grenmyr** [kristofferlind/1dv450-project-kl222jy#1]
Tjena kristoffer David Grenmyr här, jag har tittat på din apps funktionalitet och i koden.

Funtionellt:

User page uppfyller alla krav, kanske lite tråkigt att det står remove key när key borttagen. Kanske skulle användare kunna generera ny?

Bra med massor av bekräftelse och felmeddelanden.

Admin gränssnittet är väldigt snyggt, och alternativ ta bort key eller generera ny användare är grymt.

Du har använt securerandom.hex. Bra val det är något jag får ta åt mig, då jag endast genererade en slumpmässigt 8 siffrors/bokstävers kombination. Jag letade efter en inbyggt lösning för skapa unik nyckel som stöds men hittade ingen, men kommer lyfta in din i min app.

Koden:
Du validerar din email svagt utan punkter exempelvis, ett tips om du hatar fula regex, titta på gemmet:
gem 'email_validator' sen skriver du på din property i modell email:true så fixar gemmet validering.

Du har 2 automatiska tester som båda inte kompilerar, kanske borde tagit bort dom. Men ingen big deal.

Sammanfattningsvis: Stabil app inga fler anmärkningar då den är bra, ta åt dig av berömmen du fått för jag gillar den. Det enda lite svaga jag med väldigt tveksam rails kunskaper kunde se var din validering av giltig email som jag tycker var svag.

David Grenmyr

**Comment by kristofferlind** [comment]
Tackar för en gedigen genomgång. Håller med om att remove key borde försvinna där, inte alls reflekterat över det och ska ge testning en översyn. Tackar också för tipset om validering av epost, men jag är lite kluven, är det verkligen så viktigt att det är en korrekt epost? Det relevanta är väl egentligen att adressen tillhör användaren, vilket kräver en aktiveringsprocess som också borde läggas till. Lycka till med projektet!

**Comment by 1dv450** [comment]
Bra feedback!

**Comment by kristofferlind** [comment]
Knappen för att ta bort nyckel när ingen finns borta, även utökat kommentering.
