### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by HenrikGabrielsson** [kristofferlind/1dv450-project-kl222jy#2]
Hej!

Här kommer lite kritik på din applikation. Bli inte ledsen.
# Installation

Installationen var väldigt enkel och bra beskriven. Inga problem alls.
# Felhantering

Man får bra, beskrivande feedback från applikationen när man utför olika handlingar. Men det hade kanske varit bra med feedback eller en felsida när man till exempel försöker komma åt en nyckel som inte finns eller när man får en 404.
# Validering

Bra validering, förutom email-adressen som tillåter allt som har ett @ i sig.
# Säkerhet

Jag kan inte hitta några säkerhetshål, så det verkar OK ;)
# Kodkvalitet

Koden innehåller väldigt lite kommentarer, vilket hade hjälpt att förstå koden, men det kanske inte behövs eftersom koden ändå är ganska enkel att förstå. Inte mycket repetition. Bra! 
# Gränssnitt/Funktionalitet

Admin-gränssnittet är mycket snyggt och enkelt att använda. Mycket funktionalitet, och allt verkar fungera. Som användare hade det kanske varit bra om knappen “Remove key” inte fanns kvar när nyckeln redan är borttagen. Detta borde gå och fixa med en enkel if-sats.

Småfel, men i stort sätt tycker jag att allt fungerar bra och säkert. MVG++

MVH Henrik Gabrielsson, hg222aa

**Comment by kristofferlind** [comment]
Tackar för tipsen, jag ska se över felkontroller, felsidor och kommentering. Vad gäller epostvalidering har jag valt en väldigt liten kontroll eftersom det är närmast omöjligt att hitta ett korrekt regex för validering, samtidigt som det är en ganska oviktig kontroll. Jag fick dock tips om gemmet email_validator, möjligen använder jag det, men förmodligen lägger jag istället till en aktiveringsprocess. Lycka till med projektet!

**Comment by HenrikGabrielsson** [comment]
Kan hålla med om email_validator. Använde det själv i min applikation och det är väldigt smidigt och enkelt att använda. Om du däremot fixar till en aktiveringsfunktion med email så hade det ju varit ännu bättre. Tack så mycket, och lycka till du med!

**Comment by 1dv450** [comment]
Bra feedback och kommentarer. Verkar vara en stabil applikation

**Comment by kristofferlind** [comment]
Nämnd felkontroll ger 404 i produktionsläge, skippar epostaktivering tillsvidare och kommentering utökad.
