### ISSUE TITLE
Problem att få igång klienten

### ISSUE THREAD

**Issue by Pajn** [kristofferlind/1dv450-project-kl222jy#5]
Efter att ha installerat beroenden med `npm install` och försökt köra gång klienten så fick jag

```
ERROR in ./src/scripts/components/story-list.js
Module not found: Error: Cannot resolve module 'react-infinite-scroll' in /home/rasmus/tmp/1dv450-project-kl222jy/client/src/scripts/components
 @ ./src/scripts/components/story-list.js 7:21-53
```

Det gick dock smidigt att fixa med `npm install react-infinite-scroll`.

Nästa försök öppnade en browser men applikationen laddade inte alls i Firefox. I Chrome så kommer kartan fram med applikationen fungerar inte och jag får detta i konsollen

```
[HMR] Waiting for update signal from WDS...
http://localhost:3000/api/v1/stories Failed to load resource: the server responded with a status of 403 (Forbidden)
(index):1 Refused to display 'https://github.com/login/oauth/authorize?client_id=1cec10f9eb2b294a2001&red…&response_type=code&state=7f1c9ac06984b2d16988cf6fdeb27bdb5c06ffb0f7ea827e' in a frame because it set 'X-Frame-Options' to 'deny'.
2main.js:782 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.
(index):1 Refused to display 'https://github.com/login/oauth/authorize?client_id=1cec10f9eb2b294a2001&red…&response_type=code&state=b5b113e0497cff9ac29e4a744b94cd8dd41bcaf31f44afc7' in a frame because it set 'X-Frame-Options' to 'deny'.
main.js:782 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.
4main.js:20001 Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': The document is sandboxed and lacks the 'allow-same-origin' flag.
```

Jag har inte några speciella säkerhetsinställningar så jag antar att det är nått som är satt inne i koden?

**Comment by kristofferlind** [comment]
react-infinite-scroll används inte, men jag hade missat att plocka bort en referens till det vilket jag precis åtgärdat. 

Resterande felmeddelanden vet jag inte varför de uppstår, tänker mig att det är webpack-dev-server som spökar, men ska försöka undersöka saken.

**Comment by kristofferlind** [comment]
Gjort en komplett nyinstallation, lagt till information om att ändra API-nyckel för klienten, vilket jag hade missat. Jag lyckades dock inte reproducera felet. För mig fungerar nyinstallerad version av applikationen i Chrome, Firefox, Opera och Internet Explorer.

Felet kan då bero på någon globalt installerad npm modul, olika versioner av node, ruby eller något av dess paket, operativsystem, säkerhetsprogram..

**Comment by kristofferlind** [comment]
Trots ovanstående tror jag att det är webpack som är ursprungskällan till problemet, eftersom det är där en iframe nyttjas för hotreload och dylikt.

Ändrat instruktionerna till att istället köra grunt serve:dist, där webpack inte används. Mer än så kan jag dock inte göra eftersom jag inte lyckats reproducera felet och stänger därför issue.

**Comment by Pajn** [comment]
Nu lyckades jag få igång den, tolkade clientKey som den clientKey jag fick från github men testade nu med den nyckel jag fick från din applikation och då hoppade det hela igång.

Ledsen för strul, jag hinner tyvärr inte kolla mer på den idag men ska gå igenom applikationen under helgen eller i början av nästa vecka.

**Comment by kristofferlind** [comment]
Ingen fara och ingen panik =) Skönt att det löste sig iaf.
