### ISSUE TITLE
Kommentarer på koden

### ISSUE THREAD

**Issue by Pajn** [kristofferlind/1dv450-project-kl222jy#6]
Eftersom jag inte kan varken React eller Flux arkitekturen så är det svårt för mig att göra en bra review på koden så jag gör ett så bra försök jag kan.

Koden är bra uppdelad i små komponenter som konsekvent har vy-biten i botten.

Det var lite svårt för mig att hitta att stories filtreras i `main.page.js` då jag började leta i de tre story-komponenter som du har, en kommentar i t.ex. 

Det finns en del oanvända imports och filen `story-constants.js` definierar bara ett tomt objekt. Webstorm rapporterar även att en del av egenskaperna i modulobjekten är oanvända.

I `story-store.js` så har du en switch-sats med `case ActionTypes.RECEIVE_MORE_STORIES:` men ActionTypes definerar inte `RECEIVE_MORE_STORIES` vilket gör det till död kod.

I `web-api-utils.js` definerar alla anrop _ClientKey_, det hade varit bättre om den istället definierats i en konstant så att man kan ändra den på endast ett ställe.

Det är svårt för mig att kommentera på uppbyggnaden då jag inte vet hur det bör se ut. Men om jag fått den här koden att bygga vidare på så hade jag varit nöjd. Det är ganska lätt att hitta i den och det mesta håller sig mycket bra till Single Responsibility Principle.

Det har varit intressant och lärorikt att få ha tittat på ditt React-projekt, tack för det!

**Comment by kristofferlind** [comment]
Det finns en del att fundera över gällande filstruktur, framförallt i components mappen. Att data alltid kommer uppifrån är från Flux, root-komponent för gemensam data ska hantera dess data och slussa vidare nedåt. Men en kommentar om vilken komponent som är just rootkomponent i det fallet skulle kanske vara lämpligt. Kommer inte ändra det i detta projekt, men tar det med mig till exjobbet som kommer skrivas i React.

RECEIVE_MORE_STORIES fungerade, men det är väl för att jag både skickat och lyssnat efter underfined, åtgärdat. Även nästa punkt med clientkey åtgärdat medan jag ändrade instruktioner.

Tackar för en utförlig genomgång!
